### ISSUE TITLE
support for apollo cient 3?

### ISSUE THREAD

**Issue by imdadul** [helfer/apollo-link-serialize#13]
Can we use this with apollo client 3?

**Comment by helfer** [comment]
Sorry for the delay, I'll try updating the dependency later this week.

**Comment by mhmdbehairy** [comment]
@helfer Do you know an alternative solution to having a fully functional offline apollo client? Or you're not currently developing offline supported apps anymore?

**Comment by krzysztofgrowinski** [comment]
@helfer I opened a [PR](https://github.com/helfer/apollo-link-serialize/pull/23) with updated imports

**Comment by James-Firth** [comment]
@helfer Just wondering if you think you'll be able to look at @krzysztofgrowinski's PR #23 sometime soon?

I'm looking at using link serialize but currently have this branch specifically installed as a workaround and hope to see it back in the mainline :)

**Comment by helfer** [comment]
I merged @krzysztofgrowinski 's PR with support for 3.0 (and a lot of other helpful changes like prettier and eslint). Published as v4.0.0. 🎉
