### ISSUE TITLE
Publish ES5-compatible sources

### ISSUE THREAD

**Issue by nevir** [helfer/apollo-link-serialize#2]
Today, you're publishing with `import` statements, which prevents this package from being used in contexts that don't natively support `import` (e.g. node 8 and below), or aren't preprocessing their node_modules

**Comment by helfer** [comment]
Thanks for the PR @nevir!

**Comment by helfer** [comment]
Published as 2.0.0. Not that it would have mattered much, but it's still good to follow semantic versioning.
